author     = "William Trekell"
collection = "Markup Languages Revisited"
date       = "20250607"

[ai_usage]
description = """
AI was used to help brainstorm ideas, generate an outline, and suggest alternative phrasings.
"""

reason = """
To increase clarity and overcome writer’s block
"""

[human_oversight]
summary = """
I reviewed, edited, fact-checked, and finalized the content. All content decisions were made by me.
"""

article_discloser = """
TBD
"""

[ai_tools]
ideation  = """
ChatGPT-4o
"""
experiment = """
TBD
"""
draft      = """
TBD
"""

[ai_tools.refinement_prompt_example]
prompt = """
The TL;DR is meant to be a high-level summary of the entire article to help people determine if they want to read more. This is a bit long.

Hidden Dynamic: I dislike dashes as sentence segregators. I thought that was in the docs, but maybe not. Please don't ever use them. Aside from that: 1. Less about defining the how and more about identifying the role with the right domain knowledge for it to assume.

Current Landscape: This is where it gets tricky. It's about where you're reading. Social Media & LinkedIn, mostly hype and oversimplification. Blogging platforms like Medium and Substack—there is less hype, but it's replaced with a lack of experience or salesmanship. The difference being there are publications that provide real-world value with what is shared. The real knowledge is found in documentation in varying places. It's easy to get, but it doesn't show up in your inbox, so you gotta go find it.

Beyond Technical: I like the direction, but I think this is where the research I provided would pay off. It provides a reasonable overview of several items that should be considered. I'd walk away from paragraph in regular text and pull from that research to demonstrate WHAT a collaborator looks like when defined.

In key findings, what you've written isn't accurate. I'll have to dig up the specific article as I can't remember the exact details, so put this in italics to remind me.

Collaboration Revelation: It's not a revelation. The models are designed with an eagerness to please. Quick to agree to anything, overly apologetic—it's been a topic in forums on Reddit and other digital destinations. You literally have to counter-prompt to get it back to neutral and risk over-prompting and getting unfriendly results (like where we started).

Discard collaboration revelation and replace it with where most practitioners get stuck (title probably needs a change). Using that as the base, consider my guidance on the former section in regards to the new one.

Path Forward: Prompting frameworks, not technical. This sounds like you have to be a developer—you don't, once you know the way. You use the word master; don't. Ensure the rewrite is inclusive and free of bias. We're all just trying to get better or at least get by.

Additionally, I think the path forward needs to demonstrate that role prompting isn't the end-all of things, using the right markup languages, using AI prompt frameworks where they have the most benefit. We may call it engineering, but my experience is it's as much, if not more so, design.
"""

refinement = """
TBD
"""
edits      = """
Type.ai
"""
final      = """
Type.ai
"""
