# .github/workflows/readme_updater.yml

name: 'Update README Files'

on:
  push:
    branches:
      - main

jobs:
  update-readmes:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: 'Checkout Repo'
        uses: actions/checkout@v4

      - name: 'Set up Python'
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: 'List files in repository'
        run: ls -R

      # CORRECTED to point to the script's actual location inside the 'scripts' folder.
      - name: 'Run README Update Script'
        run: python ${{ github.workspace }}/scripts/update_readmes.py
      
      - name: 'Commit and Push Changes'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'docs: Auto-generate README files'
          branch: main
          commit_user_name: 'GitHub Actions Bot'
          commit_user_email: 'actions@github.com'
