# .github/workflows/readme_updater.yml

name: 'Update README Files'

# Controls when the action will run. 
# This workflow runs on pushes to the "main" branch.
on:
  push:
    branches:
      - main

jobs:
  update-readmes:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out your repository code so the workflow can access it
      - name: 'Checkout Repo'
        uses: actions/checkout@v4

      # Step 2: Set up the Python version
      - name: 'Set up Python'
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Use the latest available version of Python 3

      # Step 3: Run the Python script to generate/update READMEs
      - name: 'Run README Update Script'
        run: python update_readmes.py

      # Step 4: Commit and push the changes made by the script
      - name: 'Commit and Push Changes'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          # Required: The commit message for the automated commit
          commit_message: 'docs: Auto-generate README files'
          
          # Optional: The branch to push to. Defaults to the current branch.
          branch: main
          
          # Optional: The name of the author of the commit
          commit_user_name: 'GitHub Actions Bot'
          
          # Optional: The email of the author of the commit
          commit_user_email: 'actions@github.com'
